image: igwn/base:buster

stages:
- test
- deploy

test:
  stage: test
  before_script:
  - echo $CI_COMMIT_SHA | cut -b1-8 > gitID.txt
  script:
  - rm -rf ifo gwinc_test_report.pdf
  - mkdir ifo
  - apt-get update -qq
  - apt-get install -y -qq git python3-yaml python3-scipy python3-matplotlib python3-ipython lalsimulation-python3 python3-pypdf2 python3-h5py
  - git clone https://gitlab-ci-token:ci_token@git.ligo.org/gwinc/inspiral_range.git
  - export PYTHONPATH=inspiral_range
  - export MPLBACKEND=agg
  - python3 -m gwinc.test -r gwinc_test_report.pdf
  - for ifo in aLIGO Aplus Voyager CE1 CE2; do
  -     python3 -m gwinc $ifo -s ifo/$ifo.png
  -     python3 -m gwinc $ifo -s ifo/$ifo.h5
  - done
  - python3 -m gwinc.ifo -s ifo/all_compare.png
  after_script:
  - rm gitID.txt
  cache:
    key: "$CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME:$CI_JOB_NAME"
    untracked: true
  artifacts:
    when: always
    expire_in: 4w
    paths:
    - ifo
    - gwinc_test_report.pdf

pages:
  stage: deploy
  dependencies:
  - test
  script:
  - rm -rf public
  - mv ifo public
  - apt-get install -y -qq python3-sphinx-rtd-theme
  - cd docs
  - make html
  - cd ..
  - mv ./build/sphinx/html/* public/

  artifacts:
    paths:
    - public
    expire_in: 4w
  only:
  - master
